export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_ALL_SCHEDULE = "GET_ALL_SCHEDULE";
export const GET_SCHEDULE_BY_ID = "GET_SCHEDULE_BY_ID";
export const GET_SCHEDULE_BY_DATE = "GET_SCHEDULE_BY_DATE";
export const CREATE_SCHEDULE = "CREATE_SCHEDULE";
export const DELETE_SCHEDULE_BY_ID = "DELETE_SCHEDULE_BY_ID";
export const UPDATE_SCHEDULE_BY_ID = "UPDATE_SCHEDULE_BY_ID";

export const GET_ALL_TASK = "GET_ALL_TASK";
export const GET_TASK_BY_ID = "GET_TASK_BY_ID";
export const GET_TASK_BY_DATE = "GET_TASK_BY_DATE";
export const CREATE_TASK = "CREATE_TASK";
export const DELETE_TASK_BY_ID = "DELETE_TASK_BY_ID";
export const UPDATE_TASK_BY_ID = "UPDATE_TASK_BY_ID";

export const CREATE_TODO = "CREATE_TODO";
export const UPDATE_TODO_BY_ID = "UPDATE_TODO_BY_ID";
export const DELETE_TODO_BY_ID = "DELETE_TODO_BY_ID";

export const SET_PROFILE = "SET_PROFILE";
export const GET_PROFILE = "GET_PROFILE";

export const SEARCH_USER = "SEARCH_USER";
export const GET_ALL_FRIEND = "GET_ALL_FRIEND";
export const GET_ALL_FRIEND_REQ = "GET_ALL_FRIEND_REQ";
export const GET_ALL_FRIEND_REQ_SENT = "GET_ALL_FRIEND_REQ_SENT";
export const INVITE_FRIEND = "INVITE_FRIEND";
export const DELETE_FRIEND = "DELETE_FRIEND";
export const ACCEPT_FRIEND_REQUEST = "ACCEPT_FRIEND_REQUEST";
export const DECLINE_FRIEND_REQUEST = "DECLINE_FRIEND_REQUEST";
