export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_ALL_SCHEDULE = "GET_ALL_SCHEDULE";
export const GET_SCHEDULE_BY_ID = "GET_SCHEDULE_BY_ID";
export const CREATE_SCHEDULE = "CREATE_SCHEDULE";
export const DELETE_SCHEDULE_BY_ID = "DELETE_SCHEDULE_BY_ID";
export const UPDATE_SCHEDULE_BY_ID = "UPDATE_SCHEDULE_BY_ID";
