export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_ALL_SCHEDULE = "GET_ALL_SCHEDULE";
export const GET_SCHEDULE_BY_ID = "GET_SCHEDULE_BY_ID";
export const CREATE_SCHEDULE = "CREATE_SCHEDULE";
export const DELETE_SCHEDULE_BY_ID = "DELETE_SCHEDULE_BY_ID";
export const UPDATE_SCHEDULE_BY_ID = "UPDATE_SCHEDULE_BY_ID";

export const GET_ALL_TASK = "GET_ALL_TASK";
export const GET_TASK_BY_ID = "GET_TASK_BY_ID";
export const CREATE_TASK = "CREATE_TASK";
export const DELETE_TASK_BY_ID = "DELETE_TASK_BY_ID";
export const UPDATE_TASK_BY_ID = "UPDATE_TASK_BY_ID";

export const CREATE_TODO = "CREATE_TODO";
export const UPDATE_TODO_BY_ID = "UPDATE_TODO_BY_ID";
export const DELETE_TODO_BY_ID = "DELETE_TODO_BY_ID";
